/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and kept here so the
// Vercel build has the expected type references from the first install.
